WIP: DO NOT MERGE
We need to fix `forAllProjectsPackages`:
```
nix build .\#hydraJobs.x86_64-linux.required -j12
trace: evaluation warning: Explicitly set the ABI version of 'webkitgtk'
error:
       … while calling the 'head' builtin

         at /nix/store/y8pbnccb8bc1p8fchx7zkb0874yblrg3-source/lib/attrsets.nix:1575:11:

         1574|         || pred here (elemAt values 1) (head values) then
         1575|           head values
             |           ^
         1576|         else

       … in the left operand of the update (//) operator

         at /nix/store/qgcnijjpgkdp0w9ld0iyxv76jk2wp0xx-source/lib/default.nix:404:29:

          403|         else
          404|           (b.${name} or {}) // (a.${name} or {});
             |                             ^
          405|     }) (__attrNames (a // b)));

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: attribute 'package' missing

       at /nix/store/js4czlgq317dwr4zf1qr75xmk2pq6svr-source/nix/ouroboros-network.nix:27:27:

           26|       type = lib.types.attrsOf (lib.types.submodule ({ config, ... }: {
           27|         config = lib.mkIf config.package.isProject (cfg args);
             |                           ^
           28|       }));
 ```